### ISSUE TITLE
Explanation of branches

### ISSUE THREAD

**Issue by Lewiscowles1986** [mi-rack/Rack#4]
Is master the only branch to track here? VCVRack doesn't have branches like this, it just has 0.5 and 0.6 (as far as I can see).

Could you please explain what the three branches or git management is in this repo?

**Comment by pronvit** [comment]
I use branches the traditional way - for developing features that then will get (or not) merged into master. So basically you can ignore other branches most of the time.

**Comment by Lewiscowles1986** [comment]
Feature branches. Thanks
